name: PR
on: [pull_request]

jobs:
  pr:
    strategy:
      matrix:
        step: ['lint', 'test', 'build']
    name: ${{ matrix.step }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js version from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: yarn

      - name: ${{ matrix.step }}
        run: |
          yarn install --immutable | grep -v 'YN0013'
          yarn ${{ matrix.step }}
